version: '3'

services:
    gostarter.php-fpm:
        container_name: '${PROJECT_NAME}.php-fpm'
        build:
            args:
                USER: ${CURRENT_USER}
                UID: ${CURRENT_UID}
                WORKING_DIR: ${WORKING_DIR}
            context: ./php-fpm
        working_dir: ${WORKING_DIR}
        volumes:
            - ./../:${WORKING_DIR}
        networks:
            gostarter_default:
                aliases:
                    - '${PROJECT_NAME}.php-fpm.host'

    gostarter.nginx:
        container_name: '${PROJECT_NAME}.nginx'
        image: nginx:alpine
        volumes:
            - ./../:${WORKING_DIR}
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        working_dir: ${WORKING_DIR}
        depends_on:
            - '${PROJECT_NAME}.php-fpm'
        ports:
            - ${NGINX_PORT}:80
        networks:
            gostarter_default:
                aliases:
                    - '${PROJECT_NAME}.nginx.host'

networks:
    gostarter_default: ~
